booksite/chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    #path('', views.chat, name='chat'),    
    #path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    #path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    #path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
]

booksite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

booksite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    #path('chat/', include('chat.urls')),
    path('kyobo/<int:id>/', views.kyoboDetail),
    path('', views.home, name='home'),
]

booksite/pybo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('kyobo/<int:id>/', views.kyoboDetail),
]

booksite/chat/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

"""class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)"""

booksite/common/models.py
from django.db import models

# Create your models here.

booksite/pybo/models.py
from django.db import models

# Create your models here.

booksite/chat/forms.py
#from django import forms
#from chat.models import Question, Answer, Comment

"""class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }
"""

booksite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

booksite/chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

#from .forms import QuestionForm, AnswerForm, CommentForm
#from .models import Question, Answer, Comment

"""@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    # pybo 질문댓글등록
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)"""

booksite/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

# Create your views here.

def signup(request):
    # 계정생성
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('home')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

booksite/pybo/views.py
from django.shortcuts import render
from .kyobo import books

# Create your views here.

def home(request):
    return render(request, 'pybo/home.html', {"books":books})

def kyoboDetail(request, id):
    return render(request, 'pybo/chat-room.html')

booksite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>BOOKBOOK</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
  </head>
  <body>
    <header>
      <a href="{%url 'home'%}"><h1>북북</h1></a>

      {% if user.is_authenticated %}
      <a class="logout" href="{%url 'common:logout'%}"
        ><i class="far fa-user"></i>LOGOUT</a
      >
      {% else %}
      <a class="login" href="{%url 'common:login'%}"
        ><i class="far fa-user"></i>LOGIN</a
      >
      {% endif %}
    </header>
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %} {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
  </body>
</html>

booksite/templates/chat/chat-room.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div class="info">
  <div class="content_img">
    <img class="best" src="{% static 'images/best1.jpg' %}" alt="베스트셀러1" />
  </div>
  <div class="content_detail">
    <strong>미드나잇 라이브러리</strong>
    <div class="content_box">
      <span>매트 헤이그 지음</span>
      <span class="line">|</span>
      <span>노진선 옮김</span>
      <span class="line">|</span>
      <span>인플루엔셜</span>
      <span class="line">|</span>
      <span>2021년 04월 28일 출간</span>
    </div>
    <div class="content_box">
      <span>주간베스트 2위</span>
      <span class="line">|</span>
      <span>평점 9.5</span>
    </div>
    <div class="content_box">
      <span>정가</span>
      <span class="line">|</span>
      <span>15,800원</span>
    </div>
    <div class="description">
      <p>"후회하는 일을 되돌릴 기회가 생긴다면 다른 선택을 해보겠니?"</p>
      <span
        >어머니의 죽음, 파혼, 해고, 반려 고양이 볼츠의 죽음… 더 이상 삶을 견딜
        수 없던 주인공 노라는 자살을 결심한다. 눈을 뜬 곳은 초록색 책들로 가득한
        자정의 도서관. 친절하고 다정한 사서의 안내로 서가의 책이 모두 노라가
        살았을지도 모르는 삶들을 담고 있음을 알게 되고 노라는 《후회의 책》을
        펼쳐서, 가장 후회되는 순간 다른 선택을 했던 삶을 살아본다. 빙하학자,
        뮤지션, 동네 펍 주인, 수영 선수가 되는 삶, 평범하지만 지루한 삶, 아이가
        있는 삶 등등 가장 ‘완벽한 삶’을 찾을 때까지 수만 가지의 새로운 삶을
        거친다. 그러나 노라는 자꾸만 ‘자정의 도서관’으로 돌아오게 되고, 무엇이
        완벽한 삶인지 의문을 품는다.</span
      >
    </div>
  </div>
</div>

<div class="chat">
  <strong>진행 중인 채팅 7개</strong>
  <!-- 질문 댓글 Start 
    {% if question.comment_set.count > 0 %}
    <div class="mt-3">
    {% for comment in question.comment_set.all %}   등록한 댓글을 출력 
        <div class="comment py-2 text-muted">  댓글 각각에 comment 스타일 지정 
            <span style="white-space: pre-line;">{{ comment.content }}</span>
            <span>
                - {{ comment.author }}, {{ comment.create_date }}
                {% if comment.modify_date %}
                (수정:{{ comment.modify_date }})
                {% endif %}
            </span>
            {% if request.user == comment.author %}
            <a href="{% url 'chat:comment_modify_question' comment.id  %}" class="small">수정</a>,
            <a href="#" class="small delete" 
               data-uri="{% url 'chat:comment_delete_question' comment.id  %}">삭제</a>
            {% endif %}
        </div>
    {% endfor %}
    </div>
    {% endif %}
    <div>
        <a href="{% url 'chat:comment_create_question' question.id  %}" 
           class="small"><small>댓글 추가 ..</small></a>  댓글 추가 링크
    </div>
    질문 댓글 End -->
</div>
{% endblock %}

booksite/templates/common/login.html
{% extends "base.html" %} {% block content %}
<div class="container my-3">
  <form method="post" class="post-form" action="{% url 'common:login' %}">
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="form-group">
      <label for="username">사용자ID</label>
      <input
        type="text"
        class="form-control"
        name="username"
        id="username"
        value="{{ form.username.value|default_if_none:'' }}"
      />
    </div>
    <div class="form-group">
      <label for="password">비밀번호</label>
      <input
        type="password"
        class="form-control"
        name="password"
        id="password"
        value="{{ form.password.value|default_if_none:'' }}"
      />
    </div>
    <div class="row">
      <div class ="col-4">
        <h4>로그인</h4>
      </div>
      <div ckass="col-8 text-right">
         <span>또는 <a href="{% url 'common:signup' %}">계정을 만들기</a></div>
      </div>
    </div>
    
  </form>
</div>
{% endblock %}

booksite/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

booksite/templates/form_errors.html
{% if form.errors %} {% for field in form %} {% for error in field.errors %}
<!-- 필드 오류를 출력한다. -->
<div class="alert alert-danger">
  <strong>{{ field.label }}</strong>
  {{ error }}
</div>
{% endfor %} {% endfor %} {% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div class="alert alert-danger">
  <strong>{{ error }}</strong>
</div>
{% endfor %} {% endif %}

booksite/templates/pybo/chat-room.html
{% extends 'base.html' %} {% block content %} {% load static %}
<body>
  <header>
    <a href="{% url 'home' %}"><h1>Site Name</h1></a>
  </header>
  <div class="info">
    <div class="content_img">
      <img
        class="best"
        src="{% static 'images/best1.jpg' %}"
        alt="베스트셀러1"
      />
    </div>
    <div class="content_detail">
      <strong>미드나잇 라이브러리</strong>
      <div class="content_box">
        <span>매트 헤이그 지음</span>
        <span class="line">|</span>
        <span>노진선 옮김</span>
        <span class="line">|</span>
        <span>인플루엔셜</span>
        <span class="line">|</span>
        <span>2021년 04월 28일 출간</span>
      </div>
      <div class="content_box">
        <span>주간베스트 2위</span>
        <span class="line">|</span>
        <span>평점 9.5</span>
      </div>
      <div class="content_box">
        <span>정가</span>
        <span class="line">|</span>
        <span>15,800원</span>
      </div>
      <div class="description">
        <p>"후회하는 일을 되돌릴 기회가 생긴다면 다른 선택을 해보겠니?"</p>
        <span
          >어머니의 죽음, 파혼, 해고, 반려 고양이 볼츠의 죽음… 더 이상 삶을 견딜
          수 없던 주인공 노라는 자살을 결심한다. 눈을 뜬 곳은 초록색 책들로
          가득한 자정의 도서관. 친절하고 다정한 사서의 안내로 서가의 책이 모두
          노라가 살았을지도 모르는 삶들을 담고 있음을 알게 되고 노라는 《후회의
          책》을 펼쳐서, 가장 후회되는 순간 다른 선택을 했던 삶을 살아본다.
          빙하학자, 뮤지션, 동네 펍 주인, 수영 선수가 되는 삶, 평범하지만 지루한
          삶, 아이가 있는 삶 등등 가장 ‘완벽한 삶’을 찾을 때까지 수만 가지의
          새로운 삶을 거친다. 그러나 노라는 자꾸만 ‘자정의 도서관’으로 돌아오게
          되고, 무엇이 완벽한 삶인지 의문을 품는다.</span
        >
      </div>
    </div>
  </div>

  <div class="chat">
    <strong>진행 중인 채팅 7개</strong>
    <div class="balloon_03"></div>
  </div>
</body>
{% endblock %}

booksite/templates/pybo/home.html
{%extends "base.html"%} {%load static%} {%block content%}
<h2 class="best-seller__title">WEEKLY BEST SELLERS</h2>
<div class="best-seller__type">
  <button class="best-seller__type--button kyobo-btn">교보문고</button>
  <button class="best-seller__type--button alladdin-btn">알라딘</button>
  <button class="best-seller__type--button yes24-btn">예스24</button>
</div>
<div class="book-list">
  <div class="best-seller kyobo">
    {% for book in books %}
    <div class="best-seller__book">
      <span class="ranking first-rank">{{book.rank}}</span>
      <img src="{{book.cover}}" />
      <div class="best-seller__book--detail">
        <h3>{{book.title}}</h3>
        <span>{{book.author}}</span>
      </div>
      <div class="best-seller__book--link">
        <a href="/kyobo/{{book.id}}/"
          >Go Chat <i class="fas fa-arrow-right"></i
        ></a>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="best-seller alladdin">
    <div class="best-seller__book">
      <span class="ranking first-rank">1</span>
      <img src="{%static 'images/midnight-library.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>미드나잇 라이브러리</h3>
        <span>by 매트 헤이그</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">2</span>
      <img src="{%static 'images/puppy-poop.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>강아지똥 (25주년 특별판)</h3>
        <span>by 권정생</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">3</span>
      <img src="{%static 'images/long-night.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>긴긴밤</h3>
        <span>by 루리</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">4</span>
      <img src="{%static 'images/beyond-order.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>질서 너머</h3>
        <span>by 조던 B, 피터슨</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">5</span>
      <img src="{%static 'images/dream-department.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>달러구트 꿈 백화점</h3>
        <span>by 이미예</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">6</span>
      <img src="{%static 'images/socrates-express.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>소크라테스 익스프레스</h3>
        <span>by 에릭 와이너</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">7</span>
      <img src="{%static 'images/free-workers.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>프리 워커스</h3>
        <span>by 모빌스 그룹</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">8</span>
      <img src="{%static 'images/broken-summer.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>부서진 여름</h3>
        <span>by 이정명</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
  </div>
  <div class="best-seller yes24">
    <div class="best-seller__book">
      <span class="ranking first-rank">1</span>
      <img src="{%static 'images/beyond-order.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>질서 너머</h3>
        <span>by 조던 B, 피터슨</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">2</span>
      <img src="{%static 'images/dream-department.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>달러구트 꿈 백화점</h3>
        <span>by 이미예</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">3</span>
      <img src="{%static 'images/puppy-poop.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>강아지똥 (25주년 특별판)</h3>
        <span>by 권정생</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">4</span>
      <img src="{%static 'images/long-night.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>긴긴밤</h3>
        <span>by 루리</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">5</span>
      <img src="{%static 'images/midnight-library.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>미드나잇 라이브러리</h3>
        <span>by 매트 헤이그</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">6</span>
      <img src="{%static 'images/socrates-express.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>소크라테스 익스프레스</h3>
        <span>by 에릭 와이너</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">7</span>
      <img src="{%static 'images/free-workers.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>프리 워커스</h3>
        <span>by 모빌스 그룹</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
    <div class="best-seller__book">
      <span class="ranking">8</span>
      <img src="{%static 'images/broken-summer.jpg'%}" />
      <div class="best-seller__book--detail">
        <h3>부서진 여름</h3>
        <span>by 이정명</span>
      </div>
      <div class="best-seller__book--link">
        <a href="chat-room.html">Go Chat <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/home.js' %}"></script>
<script
  src="https://kit.fontawesome.com/041bfb30d2.js"
  crossorigin="anonymous"
></script>
{%endblock%}

booksite/templates/pybo/post_detail.html
{% extends 'base.html' %} {% block content %}
<div class="post">
  <header class="post-title">
    <h1>{{ post.title }}</h1>
    {% if post.published_date %}
    <div class="date">{{ post.published_date }}</div>
    {% endif %}
  </header>
  <p>{{ post.text|linebreaksbr }}</p>
</div>
{% endblock %}

booksite/templates/pybo/post_list.html
{% extends 'base.html' %} {% block content %} {% for post in posts %}
<div class="post">
  <header class="post-title">
    <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
    <div class="date">
      <p>published: {{ post.published_date }}</p>
    </div>
  </header>
  <p>{{ post.text|linebreaksbr }}</p>
</div>
{% endfor %} {% endblock %}