djangobookcommunity/blog/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
]

djangobookcommunity/blog/urls.py
from django.urls import path
from . import views

""" path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'), """

urlpatterns = [
    path('', views.home, name='home'),
    #path('login', views.login, name='login'),
    path('chat', views.chatRoom, name='chatRoom')
]

djangobookcommunity/bookbook/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
]

djangobookcommunity/booksite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('common/', include('common.urls')),
]

djangobookcommunity/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
]

djangobookcommunity/templates/config/urls.py
from django.contrib import admin
from django.urls import path, include
from bookbook import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('bookbook/', include('bookbook.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

djangobookcommunity/blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

djangobookcommunity/common/models.py
from django.db import models

# Create your models here.

djangobookcommunity/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

djangobookcommunity/blog/common/views.py
from django.shortcuts import render

# Create your views here.

djangobookcommunity/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post
from .kyobo import bookInfo

# Create your views here.

def home(request):
    return render(request, 'blog/home.html', {"bookInfo":bookInfo})

def login(request):
    return render(request, 'blog/login.html')

def chatRoom(request):
    return render(request, 'blog/chat-room.html')

djangobookcommunity/bookbook/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'bookbook/home.html')

djangobookcommunity/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

djangobookcommunity/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Site Name</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
  </head>{% block content %} {% endblock %}</div>
      <script
      src="https://kit.fontawesome.com/041bfb30d2.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

djangobookcommunity/blog/templates/blog/chat-room.html
{% extends 'blog/base.html' %} {% block content %} {% load static %}
<body>
  <header>
    <a href="{% url 'home' %}"><h1>Site Name</h1></a>
  </header>
  <div class="info">
    <div class="content_img">
      <img
        class="best"
        src="{% static 'images/best1.jpg' %}"
        alt="베스트셀러1"
      />
    </div>
    <div class="content_detail">
      <strong>미드나잇 라이브러리</strong>
      <div class="content_box">
        <span>매트 헤이그 지음</span>
        <span class="line">|</span>
        <span>노진선 옮김</span>
        <span class="line">|</span>
        <span>인플루엔셜</span>
        <span class="line">|</span>
        <span>2021년 04월 28일 출간</span>
      </div>
      <div class="content_box">
        <span>주간베스트 2위</span>
        <span class="line">|</span>
        <span>평점 9.5</span>
      </div>
      <div class="content_box">
        <span>정가</span>
        <span class="line">|</span>
        <span>15,800원</span>
      </div>
      <div class="description">
        <p>"후회하는 일을 되돌릴 기회가 생긴다면 다른 선택을 해보겠니?"</p>
        <span
          >어머니의 죽음, 파혼, 해고, 반려 고양이 볼츠의 죽음… 더 이상 삶을 견딜
          수 없던 주인공 노라는 자살을 결심한다. 눈을 뜬 곳은 초록색 책들로
          가득한 자정의 도서관. 친절하고 다정한 사서의 안내로 서가의 책이 모두
          노라가 살았을지도 모르는 삶들을 담고 있음을 알게 되고 노라는 《후회의
          책》을 펼쳐서, 가장 후회되는 순간 다른 선택을 했던 삶을 살아본다.
          빙하학자, 뮤지션, 동네 펍 주인, 수영 선수가 되는 삶, 평범하지만 지루한
          삶, 아이가 있는 삶 등등 가장 ‘완벽한 삶’을 찾을 때까지 수만 가지의
          새로운 삶을 거친다. 그러나 노라는 자꾸만 ‘자정의 도서관’으로 돌아오게
          되고, 무엇이 완벽한 삶인지 의문을 품는다.</span
        >
      </div>
    </div>
  </div>

  <div class="chat">
    <strong>진행 중인 채팅 7개</strong>
    <div class="balloon_03"></div>
  </div>
</body>
{% endblock %}

djangobookcommunity/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} {% block content %}
<div class="post">
  <header class="post-title">
    <h1>{{ post.title }}</h1>
    {% if post.published_date %}
    <div class="date">{{ post.published_date }}</div>
    {% endif %}
  </header>
  <p>{{ post.text|linebreaksbr }}</p>
</div>
{% endblock %}

djangobookcommunity/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %} {% block content %} {% for post in posts %}
<div class="post">
  <header class="post-title">
    <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
    <div class="date">
      <p>published: {{ post.published_date }}</p>
    </div>
  </header>
  <p>{{ post.text|linebreaksbr }}</p>
</div>
{% endfor %} {% endblock %}

djangobookcommunity/blog/templates/common/login.html
{% extends 'base.html' %} {% block content %}
    <header>
      <a href="home.html"><h1>Site Name</h1></a>
    </header>
    <div class="container my-3">
      <form method="POST" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
          <label for="user_id">ID</label><br />
          <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}"/>
        </div>
        <div class="form-group">
          <label for="user_pw">PASSWORD</label><br />
          <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}"/>
        </div>
          <button type="submit" class="btn btn-primary">로그인</button>
      </form>
      <a href="{% url 'common:signup' %}">계정이 없다면 계정을 만드세요.</a>
    </div>
  </body>
</html>
{% endblock %}

djangobookcommunity/blog/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

djangobookcommunity/templates/bookbook/chat-room.html
<!DOCTYPE html>
<html lang="ko-kr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Detail</title>
    <link rel="stylesheet" type="text/css" href="chat-room.css" />
  </head>

  <body>
    <header>
      <a href="home.html"><h1>Site Name</h1></a>
    </header>
    <div class="info">
      <div class="content_img">
        <img class="best" src="images/best1.jpg" alt="베스트셀러1" />
      </div>
      <div class="content_detail">
        <strong>미드나잇 라이브러리</strong>
        <div class="content_box">
          <span>매트 헤이그 지음</span>
          <span class="line">|</span>
          <span>노진선 옮김</span>
          <span class="line">|</span>
          <span>인플루엔셜</span>
          <span class="line">|</span>
          <span>2021년 04월 28일 출간</span>
        </div>
        <div class="content_box">
          <span>주간베스트 2위</span>
          <span class="line">|</span>
          <span>평점 9.5</span>
        </div>
        <div class="content_box">
          <span>정가</span>
          <span class="line">|</span>
          <span>15,800원</span>
        </div>
        <div class="description">
          <p>"후회하는 일을 되돌릴 기회가 생긴다면 다른 선택을 해보겠니?"</p>
          <span>어머니의 죽음, 파혼, 해고, 반려 고양이 볼츠의 죽음… 더 이상 삶을
            견딜 수 없던 주인공 노라는 자살을 결심한다. 눈을 뜬 곳은 초록색
            책들로 가득한 자정의 도서관. 친절하고 다정한 사서의 안내로 서가의
            책이 모두 노라가 살았을지도 모르는 삶들을 담고 있음을 알게 되고
            노라는 《후회의 책》을 펼쳐서, 가장 후회되는 순간 다른 선택을 했던
            삶을 살아본다. 빙하학자, 뮤지션, 동네 펍 주인, 수영 선수가 되는 삶,
            평범하지만 지루한 삶, 아이가 있는 삶 등등 가장 ‘완벽한 삶’을 찾을
            때까지 수만 가지의 새로운 삶을 거친다. 그러나 노라는 자꾸만 ‘자정의
            도서관’으로 돌아오게 되고, 무엇이 완벽한 삶인지 의문을 품는다.</span>
        </div>
      </div>
    </div>

    <div class="chat">
      <strong>진행 중인 채팅 7개</strong>
      <div class="balloon_03"></div>
    </div>
  </body>
</html>

djangobookcommunity/templates/bookbook/home.html
<!DOCTYPE html>
<html lang="ko-kr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Site Name</title>
    <link rel="stylesheet" href="home.css" />
  </head>
  <body>
    <header>
      <a href="home.html"><h1>Site Name</h1></a>
      <a class="login" href="{% url 'common:login' %}"><i class="far fa-user"></i>LOGIN</a>
    </header>
    <h2 class="best-seller__title">WEEKLY BEST SELLERS</h2>
    <div class="best-seller__type">
      <button class="best-seller__type--button comprehensive-btn">
        교보문고
      </button>
      <button class="best-seller__type--button alladdin-btn">알라딘</button>
      <button class="best-seller__type--button yes24-btn">예스24</button>
    </div>
    <div class="book-list">
      <div class="best-seller comprehensive">
        <div class="best-seller__book">
          <span class="ranking first-rank">1</span>
          <img src="images/puppy-poop.jpg" />
          <div class="best-seller__book--detail">
            <h3>강아지똥 (25주년 특별판)</h3>
            <span>by 권정생</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">2</span>
          <img src="images/midnight-library.jpg" />
          <div class="best-seller__book--detail">
            <h3>미드나잇 라이브러리</h3>
            <span>by 매트 헤이그</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">3</span>
          <img src="images/beyond-order.jpg" />
          <div class="best-seller__book--detail">
            <h3>질서 너머</h3>
            <span>by 조던 B, 피터슨</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">4</span>
          <img src="images/long-night.jpg" />
          <div class="best-seller__book--detail">
            <h3>긴긴밤</h3>
            <span>by 루리</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">5</span>
          <img src="images/dream-department.jpg" />
          <div class="best-seller__book--detail">
            <h3>달러구트 꿈 백화점</h3>
            <span>by 이미예</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">6</span>
          <img src="images/socrates-express.jpg" />
          <div class="best-seller__book--detail">
            <h3>소크라테스 익스프레스</h3>
            <span>by 에릭 와이너</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">7</span>
          <img src="images/free-workers.jpg" />
          <div class="best-seller__book--detail">
            <h3>프리 워커스</h3>
            <span>by 모빌스 그룹</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">8</span>
          <img src="images/broken-summer.jpg" />
          <div class="best-seller__book--detail">
            <h3>부서진 여름</h3>
            <span>by 이정명</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
      </div>
      <div class="best-seller alladdin">
        <div class="best-seller__book">
          <span class="ranking first-rank">1</span>
          <img src="images/midnight-library.jpg" />
          <div class="best-seller__book--detail">
            <h3>미드나잇 라이브러리</h3>
            <span>by 매트 헤이그</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">2</span>
          <img src="images/puppy-poop.jpg" />
          <div class="best-seller__book--detail">
            <h3>강아지똥 (25주년 특별판)</h3>
            <span>by 권정생</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">3</span>
          <img src="images/long-night.jpg" />
          <div class="best-seller__book--detail">
            <h3>긴긴밤</h3>
            <span>by 루리</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">4</span>
          <img src="images/beyond-order.jpg" />
          <div class="best-seller__book--detail">
            <h3>질서 너머</h3>
            <span>by 조던 B, 피터슨</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">5</span>
          <img src="images/dream-department.jpg" />
          <div class="best-seller__book--detail">
            <h3>달러구트 꿈 백화점</h3>
            <span>by 이미예</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">6</span>
          <img src="images/socrates-express.jpg" />
          <div class="best-seller__book--detail">
            <h3>소크라테스 익스프레스</h3>
            <span>by 에릭 와이너</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">7</span>
          <img src="images/free-workers.jpg" />
          <div class="best-seller__book--detail">
            <h3>프리 워커스</h3>
            <span>by 모빌스 그룹</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">8</span>
          <img src="images/broken-summer.jpg" />
          <div class="best-seller__book--detail">
            <h3>부서진 여름</h3>
            <span>by 이정명</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
      </div>
      <div class="best-seller yes24">
        <div class="best-seller__book">
          <span class="ranking first-rank">1</span>
          <img src="images/beyond-order.jpg" />
          <div class="best-seller__book--detail">
            <h3>질서 너머</h3>
            <span>by 조던 B, 피터슨</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">2</span>
          <img src="images/dream-department.jpg" />
          <div class="best-seller__book--detail">
            <h3>달러구트 꿈 백화점</h3>
            <span>by 이미예</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">3</span>
          <img src="images/puppy-poop.jpg" />
          <div class="best-seller__book--detail">
            <h3>강아지똥 (25주년 특별판)</h3>
            <span>by 권정생</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">4</span>
          <img src="images/long-night.jpg" />
          <div class="best-seller__book--detail">
            <h3>긴긴밤</h3>
            <span>by 루리</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">5</span>
          <img src="images/midnight-library.jpg" />
          <div class="best-seller__book--detail">
            <h3>미드나잇 라이브러리</h3>
            <span>by 매트 헤이그</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">6</span>
          <img src="images/socrates-express.jpg" />
          <div class="best-seller__book--detail">
            <h3>소크라테스 익스프레스</h3>
            <span>by 에릭 와이너</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">7</span>
          <img src="images/free-workers.jpg" />
          <div class="best-seller__book--detail">
            <h3>프리 워커스</h3>
            <span>by 모빌스 그룹</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
        <div class="best-seller__book">
          <span class="ranking">8</span>
          <img src="images/broken-summer.jpg" />
          <div class="best-seller__book--detail">
            <h3>부서진 여름</h3>
            <span>by 이정명</span>
          </div>
          <div class="best-seller__book--link">
            <a href="chat-room.html"
              >Go Chat <i class="fas fa-arrow-right"></i
            ></a>
          </div>
        </div>
      </div>
    </div>
    <script src="home.js"></script>
    <script
      src="https://kit.fontawesome.com/041bfb30d2.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

djangobookcommunity/templates/common/login.html
<!DOCTYPE html>
<html lang="ko-kr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="login.css" />
    <title>로그인</title>
  </head>
  <body>
    <header>
      <a href="home.html"><h1>Site Name</h1></a>
    </header>
    {% block content %}
    <div class="container my-3">
      <form method="POST" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
          <label for="user_id">ID</label><br />
          <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}"/>
        </div>
        <div class="form-group">
          <label for="user_pw">PASSWORD</label><br />
          <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}"/>
        </div>
          <button type="submit" class="btn btn-primary">로그인</button>
      </form>
      <a href="{% url 'common:signup' %}">계정이 없다면 계정을 만드세요.</a>
    </div>
  {% endblock %}
  </body>
</html>

djangobookcommunity/templates/common/signup.html
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

djangobookcommunity/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}